# Usa una imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de tu proyecto
COPY . .

# Instala las dependencias
RUN pip install --no-cache-dir numpy pandas tensorflow tensorflow_decision_forests keras fastapi uvicorn

# Comando por defecto. Este se sobreescribirá para cada servicio en docker-compose.
CMD ["python", "train.py"]
